name: Deploy MyVetPaws

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install Node dependencies
        run: npm install

      - name: Install sshpass and rsync
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass rsync

      - name: Run Deploy Script
        env:
          SSH_PASS: ${{ secrets.SSH_PASS }}
        run: |
          bash scratch/deploy.sh
